language: cpp

addons:
  apt:
    sources: 
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - g++-5
      - g++-6
      - gcc-7
      - gcc-8

matrix:
  include:
    - os: linux
      sudo: false
      env: GCC_VER="4.9"
      compiler: gcc
    - os: linux
      sudo: false
      env: GCC_VER="5"
      compiler: gcc
    - os: linux
      sudo: false
      env: GCC_VER="6"
      compiler: gcc
    - os: linux
      sudo: false
      env: GCC_VER="7"
      compiler: gcc
    - os: linux
      sudo: false
      env: GCC_VER="8"
      compiler: gcc

before_install:
  - if [ "${GCC_VER}" != "" ]; then export CXX="g++-$GCC_VER" CC="gcc-$GCC_VER" GCOV="gcov-$GCC_VER" ; fi
  - pip install --user cpp-coveralls
  - sudo apt-get install -y libgsl0-dev libopenblas-dev
  - wget https://github.com/johanjoensson/GSL-lib/archive/master.zip -O GSL-lib.zip
  - unzip GSL-lib.zip
  - cd GSL-lib-master/
  - make travis
  - cd ..

script:
    - mkdir -p build
    - make travis
