language: cpp
compiler: gcc


matrix:
        include:
          - os: linux
            addons:
              apt:
               update: true
               sources: 
                - ubuntu-toolchain-r-test
              packages:
                - g++-4.9
            sudo: false
            env: 
              - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

          - os: linux
            addons:
              apt:
               update: true
               sources: 
                - ubuntu-toolchain-r-test
              packages:
                - g++-5
            sudo: false
            env: 
              - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
          
          - os: linux
            addons:
              apt:
               update: true
               sources: 
                - ubuntu-toolchain-r-test
              packages:
                - g++-6
            sudo: false
            env: 
              - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

          - os: linux
            addons:
              apt:
               update: true
               sources: 
                - ubuntu-toolchain-r-test
              packages:
                - g++-7
            sudo: false
            env: 
              - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

          - os: linux
            addons:
              apt:
               update: true
               sources: 
                - ubuntu-toolchain-r-test
              packages:
                - g++-8
            sudo: false
            env: 
              - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"


before_install:
  - eval "${MATRIX_EVAL}"
  - pip install --user cpp-coveralls
  - sudo apt-get install -y libgsl0-dev libopenblas-dev
  - wget https://github.com/johanjoensson/GSL-lib/archive/master.zip -O GSL-lib.zip
  - unzip GSL-lib.zip
  - cd GSL-lib-master/
  - make travis
  - cd ..

script:
    - make travis
